### ISSUE TITLE
libsora.so-src CI 구축

### ISSUE THREAD

**Issue by if1live** [if1live/if1live.github.io#3]
CI빌드 스크립트 짜는 노가다하기.
C++로 빌드하는 물건도 있고 파이썬으로 굴러가는 물건도 있고 해서 CI구성하기 어려울수도 있다. 
CI하나로 여러 환경을 커버할수 있는지 확인하기

**Comment by goyusia** [comment]
빌드는 성공함. 블로그글의 링크를 새로 바꿔넣어야한다

**Comment by goyusia** [comment]
cmake 빌드는 성공. 블로그의 링크를 바꿔서 걸자
