### ISSUE TITLE
awesome 3.5 컴파일방법

### ISSUE THREAD

**Issue by if1live** [if1live/if1live.github.io#7]
우분투에서 ppa로 awesome 3.5를 까는 삽질을 햇으나 실패했다. 그래서 난 컴파일해서 깔았다. 어떤 ppa를 시도해서 망했는지, 컴파일할떄 의존성이 걸려있는 패키지 기억나는대로 명시(history참고) lightdm에 추가하는 방법등을 정리해놓는다. 이것은 irina에 재설치 하면서 문서를 검증하면 될것이다.

문서는 영어로 작성한다. 한글로 써봣자 읽을 사람이 없으니까.

**Comment by goyusia** [comment]
https://github.com/if1live/libsora.so/commit/74dd12c724dad4216f3b6c11a9e3c93db720b9d9
